### ISSUE TITLE
Installing with Hadoop?

### ISSUE THREAD

**Issue by joshzamor** [logistimo/logistimo-web-service#4]
Hi,

I've been trying to get this running on my local dev machine and while I've satisfied most of the major dependencies (MariaDB, ActiveMQ, Redis, tomcat, Zookeeper), I've been stumbling trying to get Hadoop CDH5 running correctly for this project.  So far my attempts have been using Docker hadoop images (izone/hadoop and sequenceiq/hadoop-docker), and while I have an installation running with port 9000, I receive the following message when running the ROOT.war here in tomcat7:

```
2017-06-04 13:30:36,198 INFO  [com.logistimo.services.blobstore.HDFSBlobStoreService] - HDFS Root path /user/logistimoapp/uploads/
2017-06-04 13:30:36,294 WARN  [org.apache.hadoop.util.NativeCodeLoader] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-06-04 13:30:36,734 ERROR [com.logistimo.services.blobstore.HDFSBlobStoreService] - Failed to initialize HDFS filesystem
java.io.IOException: Failed on local exception: java.io.EOFException; Host Details : local host is: "Imeshaharibika/192.168.1.102"; destination host is: "localhost":9000;
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:764)
        at org.apache.hadoop.ipc.Client.call(Client.java:1415)
        at org.apache.hadoop.ipc.Client.call(Client.java:1364)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
        at com.sun.proxy.$Proxy62.getFileInfo(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy62.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:707)
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1785)
        at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1068)
        at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1064)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1064)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1398)
        at com.logistimo.services.blobstore.HDFSBlobStoreService.init(HDFSBlobStoreService.java:80)
        at com.logistimo.services.blobstore.HDFSBlobStoreService.<init>(HDFSBlobStoreService.java:71)
        at com.logistimo.LogiAppFactory.getBlobstoreService(LogiAppFactory.java:103)
        at com.logistimo.api.controllers.BulkUploadController.<init>(BulkUploadController.java:74)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1030)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:983)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:633)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.hadoop.ipc.Client$Connection.receiveRpcResponse(Client.java:1055)
        at org.apache.hadoop.ipc.Client$Connection.run(Client.java:950)
```

A suggestion for the right direction would be helpful.  Or perhaps there's a step by step developer setup document you could share that I could learn from?

Best,
Josh

**Comment by charanm** [comment]
Hi Josh,

Can you share details on how you are running this? Are you using a Mac? Hadoop relies on hostname resolution to communicate, if you are running this inside a docker in Max, you will need to start all servers inside docker-compose, so the services can communicate. 

Other option is to run hadoop locally on Mac, that way localhost can be resolved without conflict.

```
> Download and extract Hadoop-2.3.0-cdh5.1.3 to the following folder.
/usr/local/hadoop-2.3.0-cdh5.1.3
Configure files to run hadoop in local mode (/usr/local/hadoop-2.3.0-cdh5.1.3/etc/hadoop) as shown below
core-site.xml

<configuration>
      <property>
                <name>fs.default.name</name>
                <value>hdfs://localhost:9000</value>
        </property>
</configuration>

hdfs-site.xml

<configuration>
        <property>
                <name>dfs.replication</name>
                <value>1</value>
        </property>
        <property>
                <name>dfs.namenode.name.dir</name>
                <value>/usr/local/hadoop-2.3.0-cdh5.1.3/data/namenode</value>
        </property>
        <property>
                <name>dfs.datanode.data.dir</name>
                <value>/usr/local/hadoop-2.3.0-cdh5.1.3/data/datanode</value>
        </property>
</configuration>

Slaves

localhost

> Ensure directories for datanode and namenode are created , which are configured in hdfs-site.xml
> Set HADOOP_HOME (/usr/local/hadoop-2.3.0-cdh5.1.3/) and update PATH to include > HADOOP_HOME/bin and HADOOP_HOME/sbin in bash.rc or bash_profile
> Format namenode (One-time only)
> /usr/local/hadoop-2.3.0-cdh5.1.3/bin/hadoop namenode -format
> Enable passwordless ssh
> Enable remote login
> Navigate to System Preferences > Sharing
> Once there, check the Remote Login box to enable SSH, then select the radio button labeled “All Users” from the Allow Access For section. This will in turn enable SSH for every user on the Mac. If you wish to, you can enable SSH only for select users using the other options.
> Create SSH key
> Run ssh-keygen to create ssh keys(It will prompt for values, do not give any values)
> Run cat ~/.ssh/id_rsa.pub  >> ~/.ssh/authorized_keys 
> Start Hadoop
> /usr/local/hadoop-2.3.0-cdh5.1.3/sbin/start-dfs.sh 
> Verify http://localhost:50070
```

We are working on step by step developer setup document, should be out this week.

Thanks,
Charan

**Comment by joshzamor** [comment]
Hi Charan,

I am indeed on a Mac.  Some details:

OS 10.11.6
java/c 1.8.0_131
16gb ram
Docker:
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

Thanks for the tips on running Hadoop.  I wasn't able to return to working on it today, but once I do I'll give the local install another try and report back.  Docker would be ideal though the initial creation looks non-trivial.

I'm excited to hear there will be a step by step developer document soon.  If it'd help I'll volunteer to try out early versions and help in it's creation.

Could we use this issue to track the developer doc creation?

Thanks,
Josh

**Comment by charanm** [comment]
Hi Josh,

We have put a developer setup wiki. Please give it a try and let us know, if you notice any issues.

[Setup document](https://github.com/logistimo/logistimo-web-service/wiki/Developer-setup)

Thanks,
Charan
